# Generated by Django 5.0 on 2023-12-07 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изоброжение')),
                ('full_name', models.CharField(blank=True, max_length=55, null=True, verbose_name='Фио')),
                ('direction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Направление врача')),
                ('experience', models.CharField(blank=True, max_length=255, null=True, verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'О Медике',
                'verbose_name_plural': 'O Медике',
            },
        ),
        migrations.CreateModel(
            name='Cont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер телефона')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main.doctor')),
            ],
        ),
    ]
